name: CI - Lambda SAM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Validate SAM template
        run: sam validate

      - name: Build SAM project
        run: sam build

    # Opcional: Descomenta para hacer deploy automático
    # - name: Deploy to AWS
    #   run: |
    #     sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
    #       --stack-name hello-lambda-stack \
    #       --capabilities CAPABILITY_IAM \
    #       --region us-east-1
